title: Ada's Team
baseurl: /adas-team-website/

# Handling Reading
safe: true
exclude: ["Gemfile", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files: [".git"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

timezone: "America/Edmonton"
